name: Cypress Tests
on:
  push:
    paths:
    - 'Cypress/**'
  pull_request:
    paths: 
    - 'Cypress/**'
  workflow_dispatch:
jobs:
  cypress-ghost3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: docker run --rm -t -p 2368:2368 ghost:3.41.1
          working-directory: Cypress
          wait-on: 'http://localhost:2368'
          browser: chrome
      - run: touch Cypress/cypress/screenshots && touch Cypress/cypress/videos
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots-ghost3
          path: Cypress/cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-ghost3
          path: Cypress/cypress/videos
          
  cypress-ghost4:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: docker run --rm -t -p 2368:2368 ghost:4.44.0
          working-directory: Cypress
          wait-on: 'http://localhost:2368'
          browser: chrome
      - run: touch Cypress/cypress/screenshots && touch Cypress/cypress/videos
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots-ghost4
          path: Cypress/cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos-ghost4
          path: Cypress/cypress/videos

  vrt:
    runs-on: ubuntu-latest
    needs: [cypress-ghost3, cypress-ghost4]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Ghost 3.41.1 Screenshots
        uses: actions/download-artifact@v3
        with:
          name: cypress-screenshots-ghost3
          path: ResembleJS/ghost3
      - name: Download Ghost 4.44.0 Screenshots
        uses: actions/download-artifact@v3
        with:
          name: cypress-screenshots-ghost4
          path: ResembleJS/ghost4
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ResembleJS
